name: dsouza_recipes

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cork_site: ^2.0.1
  html: ^0.15.0
  http: ^1.1.2
  build: any

dev_dependencies:
  build_runner: any
  build_web_compilers: any

