name: dsouza_recipes
dependencies:
  cork_site: ^1.0.5
  markdown: ^2.1.8
  args: ^1.6.0
  yaml: ^2.2.1
  html: ^0.14.0+4
  http: ^0.12.2
  build: any
dev_dependencies:
  build_runner: any
  build_web_compilers: any

