import 'catalog.dart';

export 'glasses.dart' show allGlasses;
export 'ice.dart' show allIceTypes;
export 'fill_lines.dart' show allFillLines;

/// Full ingredient catalog — ~85 ingredients across all categories.
const allIngredients = <Ingredient>[
  // ─── Whiskey ───────────────────────────────────────────────────────────
  Ingredient(
    id: 'rye',
    name: 'Rye',
    category: Category.whiskey,
    color: 'B8732A',
    aliases: ['rye whiskey', 'rye-whiskey'],
  ),
  Ingredient(
    id: 'bourbon',
    name: 'Bourbon',
    category: Category.whiskey,
    color: 'B8732A',
    aliases: ['bourbon whiskey', 'bourbon-whiskey'],
  ),
  Ingredient(
    id: 'scotch',
    name: 'Scotch',
    category: Category.whiskey,
    color: 'B8732A',
    aliases: ['scotch whisky', 'scotch-whisky', 'blended scotch'],
  ),
  Ingredient(
    id: 'irish-whiskey',
    name: 'Irish Whiskey',
    category: Category.whiskey,
    color: 'B8732A',
    aliases: ['irish whisky', 'irish-whisky'],
  ),
  Ingredient(
    id: 'rye-bonded',
    name: 'Bonded Rye',
    category: Category.whiskey,
    color: 'B8732A',
    aliases: ['bonded rye', 'bottled-in-bond rye', 'rye bonded'],
  ),

  // ─── Gin ───────────────────────────────────────────────────────────────
  Ingredient(
    id: 'gin',
    name: 'Gin',
    category: Category.gin,
    color: 'DCE7E3',
    aliases: ['dry gin'],
  ),
  Ingredient(
    id: 'london-dry',
    name: 'London Dry Gin',
    category: Category.gin,
    color: 'DCE7E3',
    aliases: ['london dry', 'london-dry-gin'],
  ),
  Ingredient(
    id: 'old-tom',
    name: 'Old Tom Gin',
    category: Category.gin,
    color: 'DCE7E3',
    aliases: ['old tom', 'old-tom-gin'],
  ),
  Ingredient(
    id: 'genever',
    name: 'Genever',
    category: Category.gin,
    color: 'DCE7E3',
    aliases: ['jenever', 'dutch gin', 'holland gin'],
  ),
  Ingredient(
    id: 'plymouth',
    name: 'Plymouth Gin',
    category: Category.gin,
    color: 'DCE7E3',
    aliases: ['plymouth-gin'],
  ),

  // ─── Rum ───────────────────────────────────────────────────────────────
  Ingredient(
    id: 'white-rum',
    name: 'White Rum',
    category: Category.rum,
    color: 'C88B4A',
    aliases: ['light rum', 'silver rum', 'white-rum'],
  ),
  Ingredient(
    id: 'aged-rum',
    name: 'Aged Rum',
    category: Category.rum,
    color: 'C88B4A',
    aliases: ['dark rum', 'gold rum', 'aged-rum', 'anejo rum'],
  ),
  Ingredient(
    id: 'jamaican-rum',
    name: 'Jamaican Rum',
    category: Category.rum,
    color: 'C88B4A',
    aliases: ['jamaican', 'jamaican-rum', 'pot still rum'],
  ),
  Ingredient(
    id: 'demerara-rum',
    name: 'Demerara Rum',
    category: Category.rum,
    color: 'C88B4A',
    aliases: ['guyanese rum'],
  ),
  Ingredient(
    id: 'agricole-blanc',
    name: 'Rhum Agricole Blanc',
    category: Category.rum,
    color: 'C88B4A',
    aliases: ['rhum agricole blanc', 'white agricole', 'agricole blanc'],
  ),
  Ingredient(
    id: 'agricole-aged',
    name: 'Aged Rhum Agricole',
    category: Category.rum,
    color: 'C88B4A',
    aliases: ['rhum agricole vieux', 'aged agricole', 'agricole aged'],
  ),

  // ─── Agave ─────────────────────────────────────────────────────────────
  Ingredient(
    id: 'blanco-tequila',
    name: 'Blanco Tequila',
    category: Category.agave,
    color: 'E8D49C',
    aliases: ['silver tequila', 'white tequila', 'tequila'],
  ),
  Ingredient(
    id: 'reposado-tequila',
    name: 'Reposado Tequila',
    category: Category.agave,
    color: 'E8D49C',
    aliases: ['reposado', 'rested tequila'],
  ),
  Ingredient(
    id: 'anejo-tequila',
    name: 'Anejo Tequila',
    category: Category.agave,
    color: 'E8D49C',
    aliases: ['anejo', 'aged tequila', 'añejo tequila'],
  ),
  Ingredient(
    id: 'mezcal',
    name: 'Mezcal',
    category: Category.agave,
    color: 'E8D49C',
    aliases: ['mescal', 'mezcal joven', 'espadin'],
  ),

  // ─── Brandy ────────────────────────────────────────────────────────────
  Ingredient(
    id: 'cognac',
    name: 'Cognac',
    category: Category.brandy,
    color: '7A3B1F',
    aliases: ['brandy', 'french brandy', 'vs cognac', 'vsop cognac'],
  ),
  Ingredient(
    id: 'armagnac',
    name: 'Armagnac',
    category: Category.brandy,
    color: '7A3B1F',
    aliases: ['french armagnac'],
  ),
  Ingredient(
    id: 'calvados',
    name: 'Calvados',
    category: Category.brandy,
    color: '7A3B1F',
    aliases: ['apple brandy', 'french apple brandy'],
  ),
  Ingredient(
    id: 'pisco',
    name: 'Pisco',
    category: Category.brandy,
    color: '7A3B1F',
    aliases: ['peruvian pisco', 'chilean pisco'],
  ),

  // ─── Vodka ─────────────────────────────────────────────────────────────
  Ingredient(
    id: 'vodka',
    name: 'Vodka',
    category: Category.vodka,
    color: 'EEF0F3',
    aliases: ['plain vodka'],
  ),

  // ─── Fortified Wine ────────────────────────────────────────────────────
  Ingredient(
    id: 'sweet-vermouth',
    name: 'Sweet Vermouth',
    category: Category.fortifiedWine,
    color: '6E1F2A',
    aliases: ['red vermouth', 'italian vermouth', 'rosso vermouth'],
  ),
  Ingredient(
    id: 'dry-vermouth',
    name: 'Dry Vermouth',
    category: Category.fortifiedWine,
    color: '6E1F2A',
    aliases: ['french vermouth', 'extra dry vermouth'],
  ),
  Ingredient(
    id: 'bianco-vermouth',
    name: 'Bianco Vermouth',
    category: Category.fortifiedWine,
    color: '6E1F2A',
    aliases: ['bianco', 'white vermouth'],
  ),
  Ingredient(
    id: 'blanc-vermouth',
    name: 'Blanc Vermouth',
    category: Category.fortifiedWine,
    color: '6E1F2A',
    aliases: ['blanc', 'dolin blanc'],
  ),
  Ingredient(
    id: 'lillet-blanc',
    name: 'Lillet Blanc',
    category: Category.fortifiedWine,
    color: '6E1F2A',
    aliases: ['lillet', 'lillet-blanc'],
  ),
  Ingredient(
    id: 'cocchi-americano',
    name: 'Cocchi Americano',
    category: Category.fortifiedWine,
    color: '6E1F2A',
    aliases: ['cocchi', 'cocchi-americano'],
  ),
  Ingredient(
    id: 'dry-sherry',
    name: 'Dry Sherry',
    category: Category.fortifiedWine,
    color: '6E1F2A',
    aliases: ['fino sherry', 'manzanilla', 'fino'],
  ),
  Ingredient(
    id: 'amontillado-sherry',
    name: 'Amontillado Sherry',
    category: Category.fortifiedWine,
    color: '6E1F2A',
    aliases: ['amontillado'],
  ),
  Ingredient(
    id: 'oloroso-sherry',
    name: 'Oloroso Sherry',
    category: Category.fortifiedWine,
    color: '6E1F2A',
    aliases: ['oloroso'],
  ),
  Ingredient(
    id: 'pedro-ximenez',
    name: 'Pedro Ximenez Sherry',
    category: Category.fortifiedWine,
    color: '6E1F2A',
    aliases: ['px', 'pedro ximenez', 'pedro ximénez', 'px sherry'],
  ),
  Ingredient(
    id: 'dry-marsala',
    name: 'Dry Marsala',
    category: Category.fortifiedWine,
    color: '6E1F2A',
    aliases: ['marsala', 'marsala secco'],
  ),
  Ingredient(
    id: 'white-port',
    name: 'White Port',
    category: Category.fortifiedWine,
    color: '6E1F2A',
    aliases: ['porto branco'],
  ),

  // ─── Liqueurs ──────────────────────────────────────────────────────────
  Ingredient(
    id: 'cointreau',
    name: 'Cointreau',
    category: Category.liqueur,
    color: 'B8869C',
    aliases: ['triple sec', 'orange liqueur'],
  ),
  Ingredient(
    id: 'dry-curacao',
    name: 'Dry Curacao',
    category: Category.liqueur,
    color: 'B8869C',
    aliases: ['dry curaçao', 'pierre ferrand dry curacao', 'orange curacao'],
  ),
  Ingredient(
    id: 'green-chartreuse',
    name: 'Green Chartreuse',
    category: Category.liqueur,
    color: '4A7C2E',
    aliases: ['chartreuse', 'chartreuse verte'],
  ),
  Ingredient(
    id: 'yellow-chartreuse',
    name: 'Yellow Chartreuse',
    category: Category.liqueur,
    color: 'E8C547',
    aliases: ['chartreuse jaune'],
  ),
  Ingredient(
    id: 'benedictine',
    name: 'Benedictine',
    category: Category.liqueur,
    color: 'B8869C',
    aliases: ['dom benedictine', 'b&b'],
  ),
  Ingredient(
    id: 'maraschino',
    name: 'Maraschino',
    category: Category.liqueur,
    color: 'F4EBD3',
    aliases: ['luxardo', 'maraschino liqueur', 'luxardo maraschino'],
  ),
  Ingredient(
    id: 'creme-de-violette',
    name: 'Creme de Violette',
    category: Category.liqueur,
    color: '7B5B9E',
    aliases: ['crème de violette', 'violet liqueur'],
  ),
  Ingredient(
    id: 'creme-de-cassis',
    name: 'Creme de Cassis',
    category: Category.liqueur,
    color: 'B8869C',
    aliases: ['crème de cassis', 'blackcurrant liqueur', 'cassis'],
  ),
  Ingredient(
    id: 'creme-de-menthe',
    name: 'Creme de Menthe',
    category: Category.liqueur,
    color: 'B8869C',
    aliases: ['crème de menthe', 'mint liqueur', 'green creme de menthe'],
  ),
  Ingredient(
    id: 'creme-de-cacao-white',
    name: 'White Creme de Cacao',
    category: Category.liqueur,
    color: 'B8869C',
    aliases: ['crème de cacao blanc', 'white cacao liqueur', 'clear creme de cacao'],
  ),
  Ingredient(
    id: 'creme-de-cacao-dark',
    name: 'Dark Creme de Cacao',
    category: Category.liqueur,
    color: 'B8869C',
    aliases: ['crème de cacao', 'dark cacao liqueur', 'brown creme de cacao'],
  ),
  Ingredient(
    id: 'allspice-dram',
    name: 'Allspice Dram',
    category: Category.liqueur,
    color: 'B8869C',
    aliases: ['pimento dram', 'allspice liqueur'],
  ),
  Ingredient(
    id: 'falernum',
    name: 'Falernum',
    category: Category.liqueur,
    color: 'B8869C',
    aliases: ['velvet falernum', 'john d. taylor falernum'],
  ),
  Ingredient(
    id: 'amaretto',
    name: 'Amaretto',
    category: Category.liqueur,
    color: 'B8869C',
    aliases: ['amaretto liqueur', 'disaronno', 'almond liqueur'],
  ),
  Ingredient(
    id: 'drambuie',
    name: 'Drambuie',
    category: Category.liqueur,
    color: 'B8869C',
    aliases: ['scotch liqueur', 'honey scotch liqueur'],
  ),
  Ingredient(
    id: 'blue-curacao',
    name: 'Blue Curacao',
    category: Category.liqueur,
    color: '0080C8',
    aliases: ['blue curaçao', 'blue curacao liqueur'],
  ),
  Ingredient(
    id: 'st-germain',
    name: 'St-Germain',
    category: Category.liqueur,
    color: 'B8869C',
    aliases: ['st germain', 'elderflower liqueur', 'st. germain'],
  ),
  Ingredient(
    id: 'absinthe',
    name: 'Absinthe',
    category: Category.liqueur,
    color: 'B8869C',
    aliases: ['absinthe verte', 'absinthe blanche'],
  ),

  // ─── Amari ─────────────────────────────────────────────────────────────
  Ingredient(
    id: 'campari',
    name: 'Campari',
    category: Category.amaro,
    color: 'C8102E',
    aliases: [],
  ),
  Ingredient(
    id: 'aperol',
    name: 'Aperol',
    category: Category.amaro,
    color: 'FF6B1A',
    aliases: [],
  ),
  Ingredient(
    id: 'fernet-branca',
    name: 'Fernet-Branca',
    category: Category.amaro,
    color: '2C1810',
    aliases: ['fernet', 'fernet branca'],
  ),
  Ingredient(
    id: 'averna',
    name: 'Averna',
    category: Category.amaro,
    color: '4A2418',
    aliases: ['amaro averna'],
  ),
  Ingredient(
    id: 'cynar',
    name: 'Cynar',
    category: Category.amaro,
    color: '4A2418',
    aliases: ['artichoke amaro', 'cynar 70'],
  ),
  Ingredient(
    id: 'montenegro',
    name: 'Montenegro',
    category: Category.amaro,
    color: '4A2418',
    aliases: ['amaro montenegro'],
  ),
  Ingredient(
    id: 'nonino',
    name: 'Nonino',
    category: Category.amaro,
    color: '4A2418',
    aliases: ['amaro nonino', 'amaro nonino quintessentia'],
  ),
  Ingredient(
    id: 'braulio',
    name: 'Braulio',
    category: Category.amaro,
    color: '4A2418',
    aliases: ['amaro braulio', 'braulio alpino'],
  ),

  // ─── Citrus ────────────────────────────────────────────────────────────
  Ingredient(
    id: 'lime-juice',
    name: 'Lime Juice',
    category: Category.citrus,
    color: 'E8D130',
    aliases: ['lime', 'fresh lime juice', 'fresh lime'],
  ),
  Ingredient(
    id: 'lemon-juice',
    name: 'Lemon Juice',
    category: Category.citrus,
    color: 'E8D130',
    aliases: ['lemon', 'fresh lemon juice', 'fresh lemon'],
  ),
  Ingredient(
    id: 'orange-juice',
    name: 'Orange Juice',
    category: Category.citrus,
    color: 'E8D130',
    aliases: ['orange', 'fresh orange juice', 'fresh oj', 'oj'],
  ),
  Ingredient(
    id: 'grapefruit-juice',
    name: 'Grapefruit Juice',
    category: Category.citrus,
    color: 'E8D130',
    aliases: ['grapefruit', 'fresh grapefruit juice', 'fresh grapefruit'],
  ),

  // ─── Sweeteners ────────────────────────────────────────────────────────
  Ingredient(
    id: 'simple-syrup',
    name: 'Simple Syrup',
    category: Category.sweetener,
    color: 'D4A853',
    aliases: ['1:1 syrup', 'sugar syrup'],
  ),
  Ingredient(
    id: 'demerara-syrup',
    name: 'Demerara Syrup',
    category: Category.sweetener,
    color: 'D4A853',
    aliases: ['demerara', 'demerara sugar syrup'],
  ),
  Ingredient(
    id: 'rich-demerara-syrup',
    name: 'Rich Demerara Syrup',
    category: Category.sweetener,
    color: 'D4A853',
    aliases: ['rich demerara', '2:1 demerara syrup'],
  ),
  Ingredient(
    id: 'honey-syrup',
    name: 'Honey Syrup',
    category: Category.sweetener,
    color: 'D4A853',
    aliases: ['honey', 'honey mix'],
  ),
  Ingredient(
    id: 'grenadine',
    name: 'Grenadine',
    category: Category.sweetener,
    color: 'D4A853',
    aliases: ['pomegranate syrup'],
  ),
  Ingredient(
    id: 'orgeat',
    name: 'Orgeat',
    category: Category.sweetener,
    color: 'E8DCC8',
    aliases: ['almond syrup', 'orgeat syrup'],
  ),
  Ingredient(
    id: 'sugar-cube',
    name: 'Sugar Cube',
    category: Category.sweetener,
    color: 'D4A853',
    aliases: ['sugar', 'white sugar cube', 'sugar lump'],
  ),
  Ingredient(
    id: 'gomme-syrup',
    name: 'Gomme Syrup',
    category: Category.sweetener,
    color: 'D4A853',
    aliases: ['gum syrup', 'gum arabic syrup'],
  ),

  // ─── Bitters ───────────────────────────────────────────────────────────
  Ingredient(
    id: 'angostura',
    name: 'Angostura Bitters',
    category: Category.bitters,
    color: '8B2C2C',
    aliases: ['angostura bitters', 'ango'],
  ),
  Ingredient(
    id: 'orange-bitters',
    name: 'Orange Bitters',
    category: Category.bitters,
    color: '5A1818',
    aliases: ['regan\'s orange bitters', 'orange-bitters'],
  ),
  Ingredient(
    id: 'peychauds',
    name: 'Peychaud\'s Bitters',
    category: Category.bitters,
    color: 'C83E3E',
    aliases: ['peychaud\'s', 'peychauds bitters'],
  ),

  // ─── Accents ───────────────────────────────────────────────────────────
  Ingredient(
    id: 'saline-solution',
    name: 'Saline Solution',
    category: Category.accent,
    color: '808080',
    aliases: ['saline', 'salt solution', 'salt water'],
  ),
  Ingredient(
    id: 'egg-white',
    name: 'Egg White',
    category: Category.accent,
    color: '808080',
    aliases: ['egg whites', 'egg-white', 'aquafaba'],
  ),
  Ingredient(
    id: 'soda-water',
    name: 'Soda Water',
    category: Category.accent,
    color: '808080',
    aliases: ['club soda', 'sparkling water'],
  ),
  Ingredient(
    id: 'seltzer',
    name: 'Seltzer',
    category: Category.accent,
    color: '808080',
    aliases: ['seltzer water', 'carbonated water'],
  ),
  Ingredient(
    id: 'champagne',
    name: 'Champagne',
    category: Category.accent,
    color: '808080',
    aliases: ['sparkling wine', 'brut champagne'],
  ),
  Ingredient(
    id: 'prosecco',
    name: 'Prosecco',
    category: Category.accent,
    color: '808080',
    aliases: ['italian sparkling wine'],
  ),
];
